typography_spectrum: 0.4151
color:
  brandColors:
    - '#326da7'
    - '#e5f2f8'
    - '#8e7f7a'
    - '#33c5dc'
    - '#121213'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Kucsma
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Correcto - precisely.
purpose: []
