name: Kucsma
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4151
title: Correcto - precisely.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#326da7'
    - '#e5f2f8'
    - '#8e7f7a'
    - '#33c5dc'
    - '#121213'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
