name: Kucsma
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4151
title: Correcto - precisely.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4d5353'
    - '#e2bda2'
    - '#ffffff'
    - '#281204'
    - '#ea4330'
  brandStrength: 0
  lightness: 0.3125
  saturation: 1
  rhythmicContrast: 1
purpose: []
